/**
 * Acervo base — obras para pré-cadastro.
 *
 * Não é o acervo da casa: é uma lista de obras espíritas conhecidas, para que
 * catalogar um livro vire "achar o título e acrescentar o exemplar" em vez de
 * digitar autoria toda vez. Título sem exemplar aparece na busca no grupo "a
 * casa não tem" e alimenta a lista de doações desejadas — é o D5, e é de
 * propósito.
 *
 * QUATRO FONTES, e de cada uma só fato bibliográfico — nome da obra, autoria e
 * ano. Nenhuma sinopse: sinopse é texto de alguém.
 *
 *   1. Lista pública do Centro Espírita Chico Xavier (Bauru-SP).
 *   2. Codificação de Kardec, escrita à mão. São onze obras, e o dado de uma
 *      lista de terceiro seria pior que o sabido.
 *   3. Índice de "O Caminho" (bibliadocaminho.com), que cobre a obra de Chico
 *      em quatro páginas e declara o ano da PRIMEIRA edição.
 *   4. Lista de publicações de Divaldo Franco, da Wikipédia em português.
 *
 * AS FONTES 1 E 3 SE CONFEREM. São levantamentos independentes da mesma obra,
 * e concordam sobre a autoria em 348 dos 369 títulos que ambas trazem — 94%.
 * Onde discordam, o valor da fonte 1 fica e a divergência vai para a
 * `observacao`: não há como decidir qual está certa daqui, e uma ficha que
 * avisa "as fontes discordam" vale mais que uma que finge certeza.
 *
 * O ANO É INDICATIVO. Na fonte 1 ele às vezes é o da primeira edição e às
 * vezes o de uma reimpressão (`Nos Domínios da Mediunidade` aparece como 1985,
 * e a primeira é de 1955). Nas fontes 3 e 4 costuma ser o da primeira. Em
 * todos os casos vai para `observacao` e não para campo que o sistema use: o
 * ano que vale é o do exemplar na mão, e ele mora no cadastro do exemplar.
 *
 * AUTORIA QUE NÃO DÁ PARA AFIRMAR FICA VAZIA, com o texto da fonte na
 * observação. São 23 obras — biografias, entrevistas e homenagens, que são
 * livros SOBRE Chico Xavier e não DELE. Marcá-las como psicografadas por ele
 * seria erro difícil de achar depois: a ficha ficaria plausível e errada.
 *
 * A FONTE 4 É UM ARTIGO DA WIKIPÉDIA marcado como "sem fontes" e
 * "desatualizado" pelos próprios editores. Serve para o pré-cadastro, que é
 * lista de trabalho — não serve como autoridade. Confira no exemplar.
 *
 * PARA ACRESCENTAR MAIS: é só acrescentar linha e rodar a importação de novo.
 * Ela pula o que já existe pelo título, então rodar duas vezes não duplica.
 */

// Nomes de catalogação: formal e popular juntos, como manda a especificação —
// o frequentador pede "um do Chico", não "um do Francisco Cândido".
var MEDIUM_CHICO = 'Francisco Cândido Xavier (Chico Xavier)';
var MEDIUM_DIVALDO = 'Divaldo Pereira Franco (Divaldo Franco)';

var SERIE_ANDRE_LUIZ = 'A Vida no Mundo Espiritual';
var SERIE_KARDEC = 'Obras Básicas da Codificação';

var FONTE_BAURU = 'lista do CE Chico Xavier, Bauru';
var FONTE_CAMINHO = 'índice de O Caminho';
var FONTE_KARDEC = 'codificação de Kardec';
var FONTE_DIVALDO = 'Wikipédia, publicações de Divaldo Franco';

// --- Fonte 1: [titulo, autor_espiritual, ano, ordem na série, divergência] ---
var OBRAS_CHICO_XAVIER = [
  ["A Caminho da Luz", "Emmanuel", 1939, "", ""],
  ["A Terra e o Semeador", "Emmanuel", 1975, "", " · O Caminho atribui a: Entrevistas FCX/Emmanuel"],
  ["A Verdade Responde", "Emmanuel", 1990, "", " · O Caminho atribui a: André Luiz/Emmanuel"],
  ["A Vida Conta", "Maria Dolores", 1980, "", ""],
  ["A Vida Escreve", "Hilário Silva", 1960, "", ""],
  ["A Volta", "Espíritos Diversos", 1993, "", ""],
  ["A Luz da Oração", "Espíritos Diversos", 1969, "", ""],
  ["Abrigo", "Emmanuel", 1985, "", ""],
  ["Ação e Caminho", "Emmanuel / André Luiz", 1987, "", ""],
  ["Ação e Reação", "André Luiz", 1957, "9", ""],
  ["Ação, Vida e Luz", "Espíritos Diversos", 1991, "", ""],
  ["Aceitação e Vida", "Margarida Soares", 1989, "", ""],
  ["Agenda Cristã", "André Luiz", 1948, "", ""],
  ["Agenda de Luz", "Espíritos Diversos", 1998, "", ""],
  ["Agora É o Tempo", "Emmanuel", 1984, "", ""],
  ["Algo Mais", "Emmanuel", 1980, "", ""],
  ["Alma do Povo", "Cornélio Pires", 1996, "", ""],
  ["Alma e Coração", "Emmanuel", 1969, "", ""],
  ["Alma e Luz", "Emmanuel", 1990, "", ""],
  ["Alma e Vida", "Maria Dolores", 1984, "", ""],
  ["Alma S em Desfile", "Hilário Silva", 1964, "", ""],
  ["Alvorada Cristã", "Neio Lúcio", 1949, "", ""],
  ["Alvorada do Reino", "Emmanuel", 1988, "", ""],
  ["Amigo", "Emmanuel", 1979, "", ""],
  ["Amizade", "Meimei", 1976, "", ""],
  ["Amor e Luz", "Espíritos Diversos", 1977, "", " · O Caminho atribui a: Emmanuel/Depoimentos diversos"],
  ["Amor e Saudade", "Espíritos Diversos", 1984, "", ""],
  ["Amor e Verdade", "Espíritos Diversos", 1999, "", ""],
  ["Amor sem Adeus", "Walter Perrone", 1978, "", ""],
  ["Anotações da Mediunidade", "Emmanuel", 1995, "", ""],
  ["Ante o Futuro", "Espíritos Diversos", 1990, "", ""],
  ["Antenas de Luz", "Laurinho", 1983, "", ""],
  ["Antologia da Amizade", "Emmanuel", 1995, "", ""],
  ["Antologia da Caridade", "Espíritos Diversos", 1995, "", ""],
  ["Antologia da Criança", "Espíritos Diversos", 1979, "", ""],
  ["Antologia da Esperança", "Espíritos Diversos", 1995, "", ""],
  ["Antologia da Espiritualidade", "Maria Dolores", 1971, "", ""],
  ["A Ntologia do Caminho", "Espíritos Diversos", 1997, "", ""],
  ["Antologia dos Imortais", "Espíritos Diversos", 1963, "", ""],
  ["Antologia Mediúnica do Natal", "Espíritos Diversos", 1967, "", ""],
  ["Apelos Cristãos", "Bezerra de Menezes", 1985, "", ""],
  ["Apostilas da Vida", "André Luiz", 1986, "", ""],
  ["As Palavras Cantam", "Carlos Augusto", 1993, "", ""],
  ["Assim Vencerás", "Emmanuel", 1978, "", ""],
  ["Astronautas do Além", "Espíritos Diversos", 1973, "", ""],
  ["Atenção", "Emmanuel", 1981, "", ""],
  ["Através do Tempo", "Espíritos Diversos", 1972, "", ""],
  ["Aulas da Vida", "Espíritos Diversos", 1981, "", ""],
  ["Auta de Souza", "Auta de Souza", 1976, "", ""],
  ["Ave, Cristo!", "Emmanuel", 1953, "", ""],
  ["Bastão de Arrimo", "William", 1984, "", " · O Caminho atribui a: Willian"],
  ["Bençãos de Amor", "Espíritos Diversos", 1993, "", ""],
  ["Boa Nova", "Humberto de Campos", 1941, "", ""],
  ["Brasil, Coração do Mundo, Pátria...", "Humberto de Campos", 1938, "", ""],
  ["Brilhe Vossa Luz", "Espíritos Diversos", 1987, "", ""],
  ["Buscas e Acharás", "Emmanuel / André Luiz", 1975, "", ""],
  ["Calendário Espírita", "Espíritos Diversos", 1974, "", ""],
  ["Caminho Espírita", "Espíritos Diversos", 1967, "", ""],
  ["Caminho Iluminado", "Emmanuel", 1998, "", ""],
  ["Caminho, Verdade e Vida", "Emmanuel", 1949, "", ""],
  ["Caminhos", "Emmanuel", 1981, "", ""],
  ["Caminhos da Fé", "Cornélio Pires", 1997, "", ""],
  ["Caminhos da Vida", "Cornélio Pires", 1997, "", ""],
  ["Caminhos de Volta", "Cornélio Pires", 1975, "", " · O Caminho atribui a: Autores diversos"],
  ["Caminhos do Amor", "Maria Dolores", 1983, "", ""],
  ["Canais da Vida", "Emmanuel", 1986, "", ""],
  ["Canteiro de Ideias", "Espíritos Diversos", 1999, "", ""],
  ["Caravana de Amor", "Espíritos Diversos", 1984, "", ""],
  ["Caridade", "Espíritos Diversos", 1978, "", ""],
  ["Cartas de uma Morta", "Maria João de Deus", 1935, "", ""],
  ["Cartas do Coração", "Espíritos Diversos", 1952, "", ""],
  ["Cartas do Evangelho", "Casimiro Cunha", 1941, "", ""],
  ["Cartas e Crônicas", "Irmão X", 1966, "", ""],
  ["Cartilha da Natureza", "Casimiro Cunha", 1944, "", ""],
  ["Cartilha do Bem", "Meimei", 1962, "", ""],
  ["Ceifa de Luz", "Emmanuel", 1962, "", ""],
  ["Centelhas", "Emmanuel", 1992, "", ""],
  ["Chico Xavier - Dos Hippies aos Problemas do Mundo", "Espíritos Diversos", 1972, "", ""],
  ["Cidade no Além", "André Luiz / Lucius", 1999, "", ""],
  ["Cinquenta Anos Depois", "Emmanuel", 1940, "", ""],
  ["Claramente Vivos", "Espíritos Diversos", 1979, "", ""],
  ["Coisas Deste Mundo", "Cornélio Pires", 1977, "", ""],
  ["Coletâneas do Além", "Espíritos Diversos", 1945, "", ""],
  ["Comandos do Amor", "Espíritos Diversos", 1988, "", ""],
  ["Compaixão", "Emmanuel", 1993, "", ""],
  ["Confia e Serve", "Espíritos Diversos", 1989, "", ""],
  ["Construção do Amor", "Emmanuel", 1988, "", ""],
  ["Continuidade", "Espíritos Diversos", 1990, "", ""],
  ["Contos Desta e Doutra Vida", "Irmão X", 1964, "", ""],
  ["Contos e Apólogos", "Irmão X", 1958, "", ""],
  ["Convivência", "Emmanuel", 1983, "", ""],
  ["Coração e Vida", "Maria Dolores", 1978, "", ""],
  ["Corações Renovados", "Espíritos Diversos", 1988, "", ""],
  ["Coragem", "Espíritos Diversos", 1971, "", ""],
  ["Correio do Além", "Espíritos Diversos", 1983, "", ""],
  ["Correio Fraterno", "Espíritos Diversos", 1970, "", ""],
  ["Crer e Agir", "Emmanuel / Irmão José", 1985, "", ""],
  ["Crônicas de Além-túmulo", "Humberto de Campos", 1937, "", ""],
  ["Dádivas de Amor", "Maria Dolores", 1990, "", ""],
  ["Dádivas Espirituais", "Espíritos Diversos", 1994, "", ""],
  ["Degraus da Vida", "Cornélio Pires", 1996, "", ""],
  ["Desobsessão", "André Luiz", 1964, "", ""],
  ["Deus Sempre", "Emmanuel", 1976, "", ""],
  ["Diário de Bençãos", "Cristiane", 1983, "", ""],
  ["Dicionário da Alma", "Espíritos Diversos", 1964, "", ""],
  ["Dinheiro", "Emmanuel", 1985, "", ""],
  ["Doutrina - Escola", "Espíritos Diversos", 1996, "", ""],
  ["Doutrina e Aplicação", "Espíritos Diversos", 1989, "", ""],
  ["Doutrina e Vida", "Espíritos Diversos", 1987, "", ""],
  ["E a Vida Continua", "André Luiz", 1968, "13", ""],
  ["Educandário de Luz", "Espíritos Diversos", 1984, "", ""],
  ["Elenco de Familiares", "Espíritos Diversos", 1995, "", ""],
  ["Eles Voltaram", "Espíritos Diversos", 1981, "", ""],
  ["Emmanuel", "Emmanuel", 1938, "", ""],
  ["Encontro de Paz", "Espíritos Diversos", 1973, "", ""],
  ["Encontro Marcado", "Emmanuel", 1967, "", ""],
  ["Encontros no Tempo", "Espíritos Diversos", 1979, "", ""],
  ["Endereços de Paz", "André Luiz", 1982, "", ""],
  ["Entender Conversando", "Emmanuel", 1983, "", ""],
  ["Entre a Terra e o Céu", "André Luiz", 1954, "7", ""],
  ["Entre Duas Vidas", "Espíritos Diversos", 1973, "", ""],
  ["Entre Irmãos de Outras Terras", "Espíritos Diversos", 1966, "", ""],
  ["Entrevistas", "Emmanuel", 1971, "", " · O Caminho atribui a: Entrevistas FCX/Emmanuel"],
  ["Enxugando Lágrimas", "Espíritos Diversos", 1978, "", ""],
  ["Escada de Luz", "Espíritos Diversos", 1999, "", ""],
  ["Escola no Além", "Cláudia P. Galasse", 1988, "", ""],
  ["Escrínio de Luz", "Emmanuel", 1973, "", ""],
  ["Escultores de Alma", "Espíritos Diversos", 1987, "", ""],
  ["Esperança e Alegria", "Espíritos Diversos", 1987, "", ""],
  ["Esperança e Luz", "Espíritos Diversos", 1993, "", ""],
  ["Esperança e Vida", "Espíritos Diversos", 1984, "", ""],
  ["Estamos no Além", "Espíritos Diversos", 1982, "", ""],
  ["Estamos Vivos", "Espíritos Diversos", 1992, "", ""],
  ["Estante da Vida", "Irmão X", 1969, "", ""],
  ["Estradas e Destinos", "Espíritos Diversos", 1986, "", ""],
  ["Estude e Viva", "Emmanuel / André Luiz", 1965, "", ""],
  ["Evangelho em Casa", "Meimei", 1960, "", ""],
  ["Evolução em Dois Mundos", "André Luiz", 1959, "10", ""],
  ["Excursão de Paz", "Espíritos Diversos", 1990, "", ""],
  ["Falando à Terra", "Espíritos Diversos", 1950, "", ""],
  ["Fé", "Espíritos Diversos", 1984, "", ""],
  ["Feliz Regresso", "Espíritos Diversos", 1980, "", ""],
  ["Fonte de Paz", "Espíritos Diversos", 1987, "", ""],
  ["Fonte Viva", "Emmanuel", 1956, "", ""],
  ["Fulgor no Entardecer", "Espíritos Diversos", 1991, "", ""],
  ["Gabriel", "Gabriel Casemiro Espejo", 1982, "", ""],
  ["Gaveta de Esperança", "Laurinho", 1980, "", ""],
  ["Gotas de Luz", "Casimiro Cunha", 1953, "", ""],
  ["Gotas de Paz", "Emmanuel", 1993, "", ""],
  ["Gratidão e Paz", "Espíritos Diversos", 1988, "", ""],
  ["Há Dois Mil Anos", "Emmanuel", 1940, "", ""],
  ["História de Maricota", "Casimiro Cunha", 1947, "", ""],
  ["Histórias e Anotações", "Irmão X", 1989, "", ""],
  ["Hoje", "Emmanuel", 1984, "", ""],
  ["Horas de Luz", "Espíritos Diversos", 1984, "", ""],
  ["Humorismo no Além", "Espíritos Diversos", 1983, "", ""],
  ["Ideal Espírita", "Espíritos Diversos", 1963, "", ""],
  ["Ideias e Ilustrações", "Espíritos Diversos", 1970, "", ""],
  ["Indulgência", "Emmanuel", 1989, "", ""],
  ["Instruções Psicofônicas", "Espíritos Diversos", 1956, "", ""],
  ["Instrumentos do Tempo", "Emmanuel", 1974, "", ""],
  ["Intervalos", "Espíritos Diversos", 1981, "", " · O Caminho atribui a: Emmanuel"],
  ["Irmã Vera Cruz", "Vera Cruz", 1980, "", ""],
  ["Irmão", "Emmanuel", 1980, "", ""],
  ["Janela para a Vida", "Espíritos Diversos", 1980, "", ""],
  ["Jardim da Infância", "João de Deus", 1947, "", ""],
  ["Jesus no Lar", "Neio Lucio", 1950, "", ""],
  ["Joia", "Emmanuel", 1985, "", ""],
  ["Jovens no Além", "Espíritos Diversos", 1974, "", ""],
  ["Juca Lambisca", "Casimiro Cunho", 1961, "", ""],
  ["Juntos Venceremos", "Espíritos Diversos", 1985, "", ""],
  ["Justiça Divina", "Emmanuel", 1962, "", ""],
  ["Lázaro Redivivo", "Irmão X", 1945, "", ""],
  ["Lealdade", "Maurício G. Henrique", 1982, "", ""],
  ["Leis de Amor", "Emmanuel", 1963, "", ""],
  ["Libertação", "André Luiz", 1949, "6", ""],
  ["Linha Duzentos", "Emmanuel", 1981, "", ""],
  ["Lira Imortal", "Espíritos Diversos", 1939, "", ""],
  ["Livro da Esperança", "Emmanuel", 1964, "", ""],
  ["Livro de Respostas", "Emmanuel", 1980, "", ""],
  ["Luz Acima", "Irmão X", 1948, "", ""],
  ["Luz Bendita", "Emmanuel / Esp. Diversos", 1977, "", " · O Caminho atribui a: Emmanuel/Depoimentos diversos"],
  ["Luz no Caminho", "Emmanuel", 1991, "", ""],
  ["Luz no Lar", "Espíritos Diversos", 1968, "", ""],
  ["Mãe", "Espíritos Diversos", 1971, "", ""],
  ["Mais Vida", "Espíritos Diversos", 1981, "", ""],
  ["Mãos Marcadas", "Espíritos Diversos", 1972, "", ""],
  ["Mãos Unidas", "Emmanuel", 1972, "", ""],
  ["Marcas do Caminho", "Espíritos Diversos", 1979, "", ""],
  ["Maria Dolores", "Maria Dolores", 1977, "", ""],
  ["Material de Construção", "Emmanuel", 1982, "", ""],
  ["Mecanismos da Mediunidade", "André Luiz", 1960, "11", ""],
  ["Mediunidade e Sintonia", "Emmanuel", 1985, "", ""],
  ["Mensagem do Pequeno Morto", "Neio Lúcio", 1947, "", ""],
  ["Mentores e Seareiros", "Espíritos Diversos", 1993, "", ""],
  ["Migalha", "Emmanuel", 1993, "", ""],
  ["Missionários da Luz", "André Luiz", 1945, "3", ""],
  ["Momento", "Emmanuel", 1994, "", ""],
  ["Momentos de Paz", "Emmanuel", 1980, "", ""],
  ["Moradias de Luz", "Emmanuel", 1980, "", " · O Caminho atribui a: Autores diversos"],
  ["Ninguém Morre", "Espíritos Diversos", 1983, "", ""],
  ["No Mundo Maior", "André Luiz", 1947, "5", ""],
  ["No Portal da Luz", "Emmanuel", 1967, "", ""],
  ["Nos Domínios da Mediunidade", "André Luiz", 1985, "8", ""],
  ["Nós", "Emmanuel", 1955, "", ""],
  ["Nosso Lar", "André Luiz", 1944, "1", ""],
  ["Nosso Livro", "Espíritos Diversos", 1950, "", ""],
  ["Notas do Mais Além", "Espíritos Diversos", 1995, "", ""],
  ["Notícias do Além", "Espíritos Diversos", 1980, "", ""],
  ["Novas Mensagens", "Humberto de Campos", 1940, "", ""],
  ["Novo Mundo", "Emmanuel", 1991, "", " · O Caminho atribui a: Entrevistas FCX/Emmanuel"],
  ["O Caminho Oculto", "Veneranda", 1947, "", ""],
  ["O Consolador", "Emmanuel", 1941, "", ""],
  ["O Esperanto Como Revelação", "Francisco V. P. Lorenz", 1975, "", " · O Caminho atribui a: Francisco V. Lorenz"],
  ["O Espírito da Verdade", "Emmanuel", 1962, "", " · O Caminho atribui a: Autores diversos"],
  ["O Espírito de Cornélio Pires", "Cornélio Pires", 1965, "", ""],
  ["O Essencial", "Emmanuel", 1985, "", ""],
  ["Obreiros da Vida Eterna", "André Luiz", 1946, "4", ""],
  ["Oferta de Amigo", "Cornélio Pires", 1996, "", ""],
  ["Opinião Espírita", "Emmanuel / André Luiz", 1996, "", ""],
  ["Orvalhos de Luz", "Espíritos Diversos", 1969, "", ""],
  ["Os Filhos do Grande Rei", "Veneranda", 1947, "", ""],
  ["Os Mensageiros", "André Luiz", 1944, "2", ""],
  ["Paciência", "Emmanuel", 1983, "", ""],
  ["Páginas de Fé", "Espíritos Diversos", 1988, "", ""],
  ["Páginas do Coração", "Irmã Candoca", 1951, "", ""],
  ["Pai Nosso", "Meimei", 1952, "", ""],
  ["Palavras da Coragem", "Espíritos Diversos", 1987, "", ""],
  ["Palavras de Chico Xavier", "Emmanuel", 1995, "", ""],
  ["Palavras de Emmanuel", "Emmanuel", 1954, "", ""],
  ["Palavras de Vida Eterna", "Emmanuel", 1965, "", ""],
  ["Palavras do Coração", "Meimei", 1982, "", ""],
  ["Palavras do Infinito", "Emmanuel", 1950, "", " · O Caminho atribui a: Autores diversos"],
  ["Pão Nosso", "Emmanuel", 1950, "", ""],
  ["Parnaso de Além Túmulo", "Espíritos Diversos", 1932, "", ""],
  ["Passos da Vida", "Espíritos Diversos", 1969, "", ""],
  ["Paulo e Estevão", "Emmanuel", 1942, "", ""],
  ["Paz", "Emmanuel", 1942, "", ""],
  ["Paz e Amor", "Cornélio Pires", 1996, "", ""],
  ["Paz e Libertação", "Espíritos Diversos", 1996, "", ""],
  ["Paz e Renovação", "Espíritos Diversos", 1970, "", ""],
  ["Pedaços da Vida", "Cornélio Pires", 1997, "", ""],
  ["Pensamento e Vida", "Emmanuel", 1958, "", ""],
  ["Perante Jesus", "Emmanuel", 1990, "", ""],
  ["Perdão e Vida", "Espíritos Diversos", 1999, "", ""],
  ["Pérolas de Luz", "Emmanuel", 1992, "", ""],
  ["Pérolas do Além", "Espíritos Diversos", 1952, "", ""],
  ["Pétalas de Primavera", "Espíritos Diversos", 1990, "", ""],
  ["Pétalas da Vida", "Cornélio Pires", 1997, "", ""],
  ["Pinga Fogo - Primeira Entrevista", "Espíritos Diversos", 1971, "", ""],
  ["Plantão de Respostas - Pinga Fogo II", "Espíritos Diversos", 1995, "", ""],
  ["Poetas Redivivos", "Espíritos Diversos", 1969, "", ""],
  ["Pontos e Contos", "Irmão X", 1951, "", ""],
  ["Porto de Alegria", "Espíritos Diversos", 1990, "", ""],
  ["Praça da Amizade", "Espíritos Diversos", 1982, "", ""],
  ["Presença de Laurinho", "Laurinho", 1982, "", ""],
  ["Pronto Socorro", "Emmanuel", 1980, "", ""],
  ["Quem São", "Espíritos Diversos", 1980, "", " · O Caminho atribui a: Familiares diversos1"],
  ["Recados do Além", "Emmanuel", 1978, "", ""],
  ["Recanto de Paz", "Espíritos Diversos", 1976, "", ""],
  ["Reencontros", "Espíritos Diversos", 1982, "", ""],
  ["Refúgio", "Emmanuel", 1989, "", ""],
  ["Relatos da Vida", "Irmão X", 1988, "", ""],
  ["Relicários de Luz", "Espíritos Diversos", 1962, "", ""],
  ["Religião dos Espíritos", "Emmanuel", 1960, "", ""],
  ["Renascimento Espiritual", "Espíritos Diversos", 1995, "", ""],
  ["Renúncia", "Emmanuel", 1943, "", ""],
  ["Reportagens de Além Túmulo", "Humberto de Campos", 1943, "", ""],
  ["Retornaram Contando", "Espíritos Diversos", 1984, "", ""],
  ["Retratos da Vida", "Cornélio Pires", 1973, "", ""],
  ["Rosas com Amor", "Espíritos Diversos", 1973, "", ""],
  ["Roteiro", "Emmanuel", 1952, "", ""],
  ["Rumo Certo", "Emmanuel", 1971, "", ""],
  ["Rumos da Vida", "Espíritos Diversos", 1981, "", ""],
  ["Saudação do Natal", "Espíritos Diversos", 1996, "", ""],
  ["Seara de Fé", "Espíritos Diversos", 1981, "", ""],
  ["Seara dos Médiuns", "Emmanuel", 1961, "", ""],
  ["Segue-me", "Emmanuel", 1973, "", ""],
  ["Semente", "Emmanuel", 1993, "", ""],
  ["Sementes de Luz", "Espíritos Diversos", 1986, "", ""],
  ["Senda para Deus", "Espíritos Diversos", 1997, "", ""],
  ["Sentinelas da Alma", "Meimei", 1982, "", ""],
  ["Sentinelas da Luz", "Espíritos Diversos", 1990, "", ""],
  ["Servidores no Além", "Espíritos Diversos", 1989, "", ""],
  ["Sexo e Destino", "André Luiz", 1963, "12", ""],
  ["Sinal Verde", "André Luiz", 1971, "", ""],
  ["Sínteses Doutrinárias", "Espíritos Diversos", 1995, "", ""],
  ["Somente Amor", "Maria Dolores / Meimei", 1978, "", ""],
  ["Sorrir e Pensar", "Espíritos Diversos", 1983, "", ""],
  ["Taça de Luz", "Espíritos Diversos", 1972, "", ""],
  ["Tão Fácil", "Espíritos Diversos", 1984, "", ""],
  ["Temas da Vida", "Espíritos Diversos", 1987, "", ""],
  ["Tempo de Luz", "Espíritos Diversos", 1979, "", ""],
  ["Tempo e Amor", "Espíritos Diversos", 1983, "", ""],
  ["Tempo e Nós", "Emmanuel / André Luiz", 1993, "", ""],
  ["Tende Bom Ânimo", "Espíritos Diversos", 1987, "", ""],
  ["Tesouro de Alegria", "Espíritos Diversos", 1993, "", ""],
  ["Timbolão", "Casimiro Cunha", 1962, "", ""],
  ["Tintino... O Espetáculo Continua", "Francisca Clotilde", 1976, "", ""],
  ["Tocando o Barco", "Emmanuel", 1983, "", ""],
  ["Toques da Vida", "Cornélio Pires", 1997, "", ""],
  ["Trilha de Luz", "Emmanuel", 1990, "", ""],
  ["Trovadores do Além", "Espíritos Diversos", 1965, "", ""],
  ["Trovas da Vida", "Cornélio Pires", 1999, "", ""],
  ["Trovas do Coração", "Cornélio Pires", 1997, "", ""],
  ["Trovas do Mais Além", "Espíritos Diversos", 1971, "", ""],
  ["Trovas do Outro Mundo", "Espíritos Diversos", 1968, "", ""],
  ["União em Jesus", "Espíritos Diversos", 1994, "", ""],
  ["Viajor", "Emmanuel", 1984, "", ""],
  ["Vida e Sexo", "Emmanuel", 1970, "", ""],
  ["Vida em Vida", "Espíritos Diversos", 1980, "", ""],
  ["Vinha de Luz", "Emmanuel", 1952, "", ""],
  ["Visão Nova", "Emmanuel", 1986, "", " · O Caminho atribui a: Autores diversos"],
  ["Vitória", "Espíritos Diversos", 1986, "", ""],
  ["Vivendo Sempre", "Espíritos Diversos", 1981, "", ""],
  ["Viveremos Sempre", "Espíritos Diversos", 1994, "", ""],
  ["Volta Bocage", "Manuel M. B. du Bocage", 1947, "", ""],
  ["Voltei", "Irmão Jacob", 1949, "", ""],
  ["Vozes da Outra Margem", "Espíritos Diversos", 1986, "", ""],
  ["Vozes do Grande Além", "Espíritos Diversos", 1957, "", ""],
];

// --- Fonte 2: [titulo, ano, ordem entre as obras básicas] -------------------
var OBRAS_KARDEC = [
  ["O Livro dos Espíritos", 1857, 1],
  ["O Livro dos Médiuns", 1861, 2],
  ["O Evangelho segundo o Espiritismo", 1864, 3],
  ["O Céu e o Inferno", 1865, 4],
  ["A Gênese", 1868, 5],
  ["O que é o Espiritismo", 1859],
  ["O Espiritismo em sua Mais Simples Expressão", 1862],
  ["Instruções Práticas sobre as Manifestações Espíritas", 1858],
  ["Viagem Espírita em 1862", 1862],
  ["Obras Póstumas", 1890],
  ["Revista Espírita", 1858],
];

// --- Fonte 3: [titulo, autor_espiritual, ano da 1ª ed., nota] ---------------
//
// Autor espiritual vazio = obra SOBRE Chico Xavier, e a nota é o que o site
// dizia, sem interpretação nossa. Com autor preenchido, a nota é a eventual
// divergência com a fonte 1.
var OBRAS_CHICO_COMPLEMENTO = [
  ["… E o amor continua", "Espíritos Diversos", 1983, ""],
  ["A semente de mostarda", "Emmanuel", 1990, ""],
  ["Abençoa sempre", "Espíritos Diversos", 1993, ""],
  ["Abençoando nosso Brasil, com Jesus e por Jesus", "Espíritos Diversos", 2007, ""],
  ["Adeus solidão", "Espíritos Diversos", 1982, ""],
  ["Agência de Notícias", "Jair Presente", 1986, ""],
  ["Almas em desfile", "Hilário Silva", 1961, ""],
  ["Amanhece", "Espíritos Diversos", 1976, ""],
  ["Assembleia de Luz", "Espíritos Diversos", 1988, ""],
  ["Assuntos da vida e da morte", "Espíritos Diversos", 1991, ""],
  ["Augusto vive", "Augusto Cezar Netto", 1981, ""],
  ["Baú de casos", "Cornélio Pires", 1977, ""],
  ["Bazar da Vida", "Jair Presente", 1985, ""],
  ["Bênção de paz", "Emmanuel", 1971, ""],
  ["Bezerra, Chico e você", "Bezerra de Menezes", 1973, ""],
  ["Brasil, coração do mundo, pátria do Evangelho", "Humberto de Campos", 1938, ""],
  ["Brilhantes no caminho", "Espíritos Diversos", 2023, ""],
  ["Busca e acharás", "", 1976, "(não informada)"],
  ["Caderno de mensagens", "Espíritos Diversos", '', ""],
  ["Calma", "Emmanuel", 1979, ""],
  ["Carmelo, ele mesmo", "Carmelo Grisi", 1991, ""],
  ["Cartas do Alto", "Espíritos Diversos", 2017, ""],
  ["Cartas do Evangelho e outros poemas", "Casimiro Cunha", 1940, ""],
  ["Chão de flores", "Espíritos Diversos", 1975, ""],
  ["Chico no Monte Carmelo", "", 2004, "Autores diversos"],
  ["Chico Xavier — Mandato de amor", "", 1992, "Autores diversos"],
  ["Chico Xavier e suas mensagens no Anuário Espírita", "", 2017, "(não informada)"],
  ["Chico Xavier em Goiânia", "", 1978, "Entrevistando Emmanuel"],
  ["Chico Xavier inédito", "", 2004, "Autores diversos"],
  ["Chico Xavier pede licença", "", 1972, "Autores diversos"],
  ["Chico Xavier, 100 anos de amor", "", 2010, "Autores diversos"],
  ["Chico Xavier, a aurora de uma vida entre o Céu e a Terra", "", 2012, "Autores diversos subscritos por F. Xavier"],
  ["Chico Xavier, coração missionário", "", 2009, "Autores diversos"],
  ["Chico Xavier, dos hippies aos problemas do mundo", "", 1972, "Entrevistando Emmanuel"],
  ["Chico Xavier, exemplo de amor", "", 2010, "Autores diversos"],
  ["Chico Xavier, o referencial", "", 2010, "(não informada)"],
  ["Chico Xavier: O Primeiro Livro", "", 2010, "Autores diversos"],
  ["Coletânea do Além", "Espíritos Diversos", 1945, ""],
  ["Colheita do bem", "Neio Lúcio", 2010, ""],
  ["Companheiro", "Emmanuel", 1977, ""],
  ["Confia e segue", "Emmanuel", 1984, ""],
  ["Conversa firme", "Cornélio Pires", 1975, ""],
  ["Crianças no Além", "Marcos Hideo Hayashi", 1977, " · O Caminho atribui a: Marcos"],
  ["Cura", "Espíritos Diversos", 1988, ""],
  ["Depois da travessia", "Espíritos Diversos", 2013, ""],
  ["Deus aguarda", "Meimei", 1980, ""],
  ["Deus conosco", "Emmanuel", 2007, ""],
  ["Diálogo dos vivos", "Espíritos Diversos", 1974, ""],
  ["Doutrina de Luz", "Emmanuel", 1990, ""],
  ["Doutrina-escola", "Espíritos Diversos", 1996, ""],
  ["Emmanuel responde", "", 2010, "F. C. Xavier / Henrique Rodrigues / Entrevista"],
  ["Endereços da paz", "André Luiz", 1982, ""],
  ["Entes queridos", "Espíritos Diversos", 1982, ""],
  ["Escultores de almas", "Espíritos Diversos", 1988, ""],
  ["Espera servindo", "Emmanuel", 1985, ""],
  ["Estrelas no chão", "Espíritos Diversos", 1987, ""],
  ["Falou e disse", "Augusto Cezar Netto", 1978, ""],
  ["Família", "Espíritos Diversos", 1981, ""],
  ["Fé e vida", "Espíritos Diversos", 2014, ""],
  ["Fé, paz e amor", "Emmanuel", 1989, ""],
  ["Festa de paz", "Espíritos Diversos", 1986, ""],
  ["Filhos voltando", "Espíritos Diversos", 1982, " · O Caminho atribui a: J. R. P. da Silva e J. R. P. Cassiano"],
  ["Fotos da vida", "Augusto Cezar Netto", 1989, ""],
  ["Harmonização", "Emmanuel", 1990, ""],
  ["Hora certa", "Emmanuel", 1987, ""],
  ["Indicações do caminho", "Carlos Augusto", 1994, ""],
  ["Inspiração", "Emmanuel", 1978, ""],
  ["Intercâmbio do bem", "Espíritos Diversos", 1987, ""],
  ["Irmãos unidos", "Espíritos Diversos", 1988, ""],
  ["Jesus em nós", "Emmanuel", 1987, ""],
  ["Lar-oficina, esperança e trabalho", "Espíritos Diversos", 1988, ""],
  ["Levantar e seguir", "Emmanuel", 1992, ""],
  ["Loja de alegria", "Jair Presente", 1985, ""],
  ["Luz e vida", "Emmanuel", 1986, ""],
  ["Luz na Escola", "Espíritos Diversos", 2010, ""],
  ["Mais luz", "Batuíra", 1970, ""],
  ["Mais perto", "Emmanuel", 1983, ""],
  ["Mensagens de Inês de Castro", "Inês de Castro", 2006, ""],
  ["Mensagens que confortam", "Ricardo Tadeu", 1983, ""],
  ["Militares no Além", "Espíritos Diversos", 2008, ""],
  ["Missão cumprida", "Espíritos Diversos", 2004, ""],
  ["Momentos de ouro", "Espíritos Diversos", 1977, ""],
  ["Monte acima", "Emmanuel", 1985, ""],
  ["Na era do Espírito", "Espíritos Diversos", 1973, ""],
  ["Na hora do testemunho", "Espíritos Diversos", 1978, ""],
  ["Nascer e renascer", "Emmanuel", 1985, ""],
  ["Natal de Sabina", "Francisca Clotilde", 1973, ""],
  ["Neste instante", "Emmanuel", 2000, ""],
  ["No mundo de Chico Xavier", "", 1968, "Entrevistas"],
  ["Notáveis reportagens com Chico Xavier", "", 2002, "(não informada)"],
  ["Novamente em casa", "Espíritos Diversos", 1984, ""],
  ["Novos horizontes", "Espíritos Diversos", 1996, ""],
  ["O Evangelho de Chico Xavier", "", 2000, "Chico Xavier (Encarnado)"],
  ["O Evangelho por Emmanuel", "Emmanuel", 2014, ""],
  ["Orvalho de Luz", "Espíritos Diversos", 1969, ""],
  ["Os dois maiores amores", "Espíritos Diversos", 1983, ""],
  ["Páginas de gratidão", "", 2020, "Títulos de Cidadania concedidos a Francisco Cândido Xavier"],
  ["Palavras sublimes", "Espíritos Diversos", 2014, ""],
  ["Palco iluminado", "Jair Presente", 1988, ""],
  ["Palpitante entrevista com o outro mundo", "", '', "(Entrevistando Emmanuel) — Isaltino da Silveira Filho"],
  ["Parnaso de Além-Túmulo", "Espíritos Diversos", 1932, ""],
  ["Pássaros humanos", "Espíritos Diversos", 1993, ""],
  ["Paz e alegria", "Espíritos Diversos", 1981, ""],
  ["Pétalas da primavera", "Espíritos Diversos", 1990, ""],
  ["Pinga-fogo", "", '', "Entrevistas/Emmanuel"],
  ["Pingo de luz", "Carlos Augusto", 1994, ""],
  ["Plantão da paz", "Emmanuel", 1988, ""],
  ["Plantão de respostas", "", 1995, "Entrevistas"],
  ["Ponto de encontro", "Jair Presente", 1986, ""],
  ["Preito de amor", "Espíritos Diversos", 1993, ""],
  ["Presença de Chico Xavier", "", 1970, "Depoimentos diversos e Mensagens familiares"],
  ["Presença de luz", "Augusto Cezar Netto", 1984, ""],
  ["Quando se pretende falar da Vida", "Roberto Muszkat", 1984, ""],
  ["Queda e ascensão da casa dos benefícios", "Bezerra de Menezes", 1991, ""],
  ["Rapidinho", "Jair Presente", 1989, ""],
  ["Realmente", "Espíritos Diversos", 2005, ""],
  ["Recados da vida", "Espíritos Diversos", 1983, ""],
  ["Reconforto", "Emmanuel", 1986, ""],
  ["Registros imortais", "Espíritos Diversos", 2013, ""],
  ["Relicário de luz", "Espíritos Diversos", 1962, ""],
  ["Reportagens de Além-túmulo", "Humberto de Campos", 1943, ""],
  ["Resgate e amor", "Tiaminho", 1986, ""],
  ["Respostas da vida", "André Luiz", 1975, ""],
  ["Revelação", "Jair Presente", 1992, ""],
  ["Rolando, uma vida de renúncia e trabalho", "Rolando Ramacciotti", 2013, ""],
  ["Roseiral de luz", "Espíritos Diversos", 1988, ""],
  ["Seguindo juntos", "Espíritos Diversos", 1982, ""],
  ["Semeador em tempos novos", "Emmanuel", 1989, ""],
  ["Sementeira de luz", "Neio Lúcio", 2006, ""],
  ["Sementeira de paz", "Neio Lúcio", 2010, ""],
  ["Sinais de rumo", "Espíritos Diversos", 1979, ""],
  ["Somos seis", "Espíritos Diversos", 1976, ""],
  ["Tintino… O espetáculo continua", "Francisca Clotilde", '', ""],
  ["Trevo de ideias", "Emmanuel", 1987, ""],
  ["Trovas do Mais-Além", "Espíritos Diversos", 1971, ""],
  ["Tudo virá a seu tempo", "Elcio Tumenas", 2003, ""],
  ["Uma vida de amor e caridade", "Espíritos Diversos", 1992, " · O Caminho atribui a: Izabel Bueno/Autores diversos"],
  ["Urgência", "Emmanuel", 1980, ""],
  ["Venceram", "Espíritos Diversos", 1983, ""],
  ["Verdade e amor", "Espíritos Diversos", 2015, ""],
  ["Vereda de luz", "Espíritos Diversos", 1990, ""],
  ["Viagem sem adeus", "Cláudio R. A. Nascimento", 1999, ""],
  ["Viajaram mais cedo", "Espíritos Diversos", 1985, ""],
  ["Viajores da Luz", "Espíritos Diversos", 1981, ""],
  ["Vida além da vida", "Lineu de Paula Leão Júnior", 1988, " · O Caminho atribui a: Lineu de Paula Leão Jr."],
  ["Vida e caminho", "Espíritos Diversos", 1994, ""],
  ["Vida no Além", "Espíritos Diversos", 1980, ""],
  ["Vida nossa vida", "Espíritos Diversos", 1983, ""],
];

// --- Fonte 4: [titulo, autor_espiritual, ano] -------------------------------
var OBRAS_DIVALDO_FRANCO = [
  ["...Até o Fim dos Tempos", "Amélia Rodrigues", 2015],
  ["...E o amor continua", "Espíritos diversos", 2016],
  ["100 Reflexões filosóficas", "Victor Hugo", 2009],
  ["A Busca da Perfeição", "Eros", 1993],
  ["A lenda do esconderijo seguro", "Selma Lagerlöf", 1998],
  ["A lenda dos milagres do amor", "Selma Lagerlöf", 1994],
  ["A Lição Do Semeador", "Selma Lagerlöf", 1975],
  ["À Luz do Espiritismo", "Vianna de Carvalho", 1992],
  ["A mensagem do amor imortal", "Amélia Rodrigues", 1964],
  ["A um passo da imortalidade", "Eros", 1994],
  ["Adolescência e Vida", "Joanna de Ângelis", 1997],
  ["Alegria de Viver", "Joanna de Ângelis", 1987],
  ["Além da Morte", "Otília Gonçalves", 1964],
  ["Alerta", "Joanna de Ângelis", 1981],
  ["Amanhecer de Uma Nova Era", "Manoel Philomeno de Miranda", 2012],
  ["Amor", "Espíritos diversos", 1964],
  ["Amor e Sexualidade - A Conquista da Alma", "Joanna de Ângelis", 2018],
  ["Amor, Imbatível Amor", "Joanna de Ângelis", 2002],
  ["Amorterapia", "Joanna de Ângelis", 2000],
  ["Antologia Espiritual", "Espíritos diversos", 1979],
  ["Aos Espíritas", "Espíritos diversos", 1974],
  ["Após a tempestade", "Joanna de Ângelis", 1977],
  ["Árdua Ascensão", "Victor Hugo", 1994],
  ["Atendimento Fraterno", "Manoel Philomeno de Miranda", 2010],
  ["Atitudes Renovadas", "Joanna de Ângelis", 2009],
  ["Atualidade do Pensamento Espírita", "Vianna de Carvalho", 2005],
  ["Autodescobrimento: uma busca interior", "Joanna de Ângelis", 1995],
  ["Bênçãos de Natal", "Joanna de Ângelis", 1998],
  ["Benesses Natalinas", "Joanna de Ângelis", 2009],
  ["Calvário de Libertação", "Victor Hugo", 1997],
  ["Celeiro de Bênçãos", "Joanna de Ângelis", 1974],
  ["Compromissos de amor", "Espíritos diversos", 2014],
  ["Compromissos iluminativos", "Bezerra de Menezes", 1990],
  ["Conflitos Existenciais", "Joanna de Ângelis", 2005],
  ["Constelação familiar", "Joanna de Ângelis", 2008],
  ["Convites da Vida", "Joanna de Ângelis", 1972],
  ["Crestomatia da Imortalidade", "Espíritos diversos", 1969],
  ["Dádivas do Natal", "Joanna de Ângelis", 2010],
  ["Depoimentos vivos", "Espíritos diversos", 1975],
  ["Depois da vida", "Espíritos diversos", 1984],
  ["Desperte e seja feliz", "Joanna de Ângelis", 1996],
  ["Diamantes Fatídicos", "Victor Hugo", 2018],
  ["Dias gloriosos", "Joanna de Ângelis", 2002],
  ["Dias Venturosos", "Amélia Rodrigues", 2015],
  ["Dimensões da verdade", "Joanna de Ângelis", 1965],
  ["Diretrizes de Segurança", "Espíritos diversos", 1995],
  ["Diretrizes para o êxito", "Joanna de Ângelis", 2004],
  ["Diretrizes para uma vida feliz", "Marco Prisco", 2011],
  ["Do Abismo às Estrelas", "Victor Hugo", 1975],
  ["Em algum Lugar do Futuro", "Eros", 2007],
  ["Em busca da verdade", "Joanna de Ângelis", 2009],
  ["Em louvor à vida", "Lourival Perri Chefaly", 1987],
  ["Ementário Espírita", "Marco Prisco", 2015],
  ["Encontro com a paz e a saúde", "Joanna de Ângelis", 2007],
  ["Enfoques Espíritas", "Vianna de Carvalho", 2009],
  ["Entre os dois mundos", "Manoel Philomeno de Miranda", 2005],
  ["Entrega-Te A Deus", "Joanna de Ângelis", 2010],
  ["Episódios Diários", "Joanna de Ângelis", 1986],
  ["Espelho d’Alma", "Ignotus", 1980],
  ["Espiritismo e vida", "Vianna de Carvalho", 1979],
  ["Espírito e Vida", "Joanna de Ângelis", 1967],
  ["Estesia", "Rabindranath Tagore", 2002],
  ["Estudos Espíritas", "Joanna de Ângelis", 1982],
  ["Exaltação à Vida", "Espíritos diversos", 1987],
  ["Faze Isso e Viverás", "Marco Prisco", 2002],
  ["Filhos de Deus", "Joanna de Ângelis", 1986],
  ["Filigranas de Luz", "Rabindranath Tagore", 1965],
  ["Florações Evangélicas", "Joanna de Ângelis", 2017],
  ["Fonte de Luz", "Joanna de Ângelis", 2000],
  ["Francisco, o Sol de Assis", "Joanna de Ângelis", 2014],
  ["Garimpo de Amor", "Joanna de Ângelis", 2003],
  ["Glossário Espírita – Cristão", "Marco Prisco", 2015],
  ["Grilhões Partidos", "Manoel Philomeno de Miranda", 1974],
  ["Há Flores no Caminho", "Amélia Rodrigues", 2002],
  ["Heranças de Amor", "Eros", 2020],
  ["Ilumina-te", "Joanna de Ângelis", 2013],
  ["Iluminação interior", "Joanna de Ângelis", 2006],
  ["Impermanência e Imortalidade", "Carlos Torres Pastorino", 2017],
  ["Intercâmbio Mediúnico", "João Cléofas", 2002],
  ["Jesus e Atualidade", "Joanna de Ângelis", 1989],
  ["Jesus e o evangelho à luz da psicologia profunda", "Joanna de Ângelis", 2001],
  ["Jesus e vida", "Joanna de Ângelis", 2017],
  ["Joanna de Ângelis Responde", "Joanna de Ângelis", 1999],
  ["Lampadário Espírita", "Joanna de Ângelis", 1969],
  ["Legado Kardequiano", "Marco Prisco", 1966],
  ["Leis Morais da Vida", "Joanna de Ângelis", 1976],
  ["Liberta-te do Mal", "Joanna de Ângelis", 2012],
  ["Libertação do sofrimento", "Joanna de Ângelis", 2008],
  ["Libertação pelo Amor", "Joanna de Ângelis", 2005],
  ["Lições para a Felicidade", "Joanna de Ângelis", 2013],
  ["Loucura e obsessão", "Manoel Philomeno de Miranda", 1988],
  ["Luz da Esperança", "Joanna de Ângelis", 1986],
  ["Luz do mundo", "Amélia Rodrigues", 2016],
  ["Luz nas Trevas", "Joanna de Ângelis", 2018],
  ["Luz viva", "Espíritos diversos", 1984],
  ["Luzes do alvorecer", "Espíritos diversos", 2001],
  ["Mediunidade: Desafios e Bençãos", "Manoel Philomeno de Miranda", 2012],
  ["Médiuns e mediunidade", "Vianna de Carvalho", 2015],
  ["Messe de amor", "Joanna de Ângelis", 1964],
  ["Momentos de Alegria", "Joanna de Ângelis", 1989],
  ["Momentos de Consciência", "Joanna de Ângelis", 1991],
  ["Momentos de Coragem", "Joanna de Ângelis", 1988],
  ["Momentos de Decisão", "Marco Prisco", 2015],
  ["Momentos de Esperança", "Joanna de Ângelis", 1988],
  ["Momentos de Felicidade", "Joanna de Ângelis", 1990],
  ["Momentos de Harmonia", "Joanna de Ângelis", 1991],
  ["Momentos de Iluminação", "Joanna de Ângelis", 1990],
  ["Momentos de Meditação", "Joanna de Ângelis", 1988],
  ["Momentos de Renovação", "Joanna de Ângelis", 1996],
  ["Momentos de Saúde", "Joanna de Ângelis", 1992],
  ["Momentos de saúde e de consciência", "Joanna de Ângelis", 2003],
  ["Momentos de Sublimação", "Joanna de Ângelis / Vianna de Carvalho", 2018],
  ["Momentos Enriquecedores", "Joanna de Ângelis", 1994],
  ["Nas fronteiras da loucura", "Manoel Philomeno de Miranda", 1982],
  ["Nascente de Bênçãos", "Joanna de Ângelis", 2001],
  ["No Limiar do Infinito", "Joanna de Ângelis", 1977],
  ["No longe do jardim", "Eros", 1975],
  ["No rumo da felicidade", "Joanna de Ângelis", 2001],
  ["No Rumo do Mundo de Regeneração", "Manoel Philomeno de Miranda", 2020],
  ["Nos Bastidores da Obsessão", "Manoel Philomeno de Miranda", 1970],
  ["O amor como solução", "Joanna de Ângelis", 2006],
  ["O Colar de Diamantes", "Joanna de Ângelis", 2014],
  ["O despertar do espírito", "Joanna de Ângelis", 2000],
  ["O Homem Integral", "Joanna de Ângelis", 1990],
  ["O Semeador", "Amélia Rodrigues", 2015],
  ["O Ser Consciente", "Joanna de Ângelis", 1993],
  ["O vencedor", "Amélia Rodrigues", 1965],
  ["Oferenda", "Joanna de Ângelis", 1980],
  ["Os caminhos do amor", "Rabindranath Tagore", 1989],
  ["Otimismo", "Joanna de Ângelis", 1983],
  ["Painéis da Obsessão", "Manoel Philomeno de Miranda", 1984],
  ["Palavras de luz", "Espíritos diversos", 1993],
  ["Panoramas da Vida", "Ignotus", 2002],
  ["Párias em redenção", "Victor Hugo", 1971],
  ["Pássaros Livres", "Rabindranath Tagore", 2019],
  ["Paz íntima", "Eros", 2018],
  ["Pelos caminhos de Jesus", "Amélia Rodrigues", 2015],
  ["Pensamentos de Joanna de Ângelis", "Joanna de Ângelis", 2014],
  ["Perfis da Vida", "Guaracy Paraná Vieira", 2011],
  ["Perturbações Espirituais", "Manoel Philomeno de Miranda", 2015],
  ["Plenitude", "Joanna de Ângelis", 1991],
  ["Poemas de Paz", "Simbá", 2002],
  ["Primícias do Reino", "Amélia Rodrigues", 1968],
  ["Psicologia da Gratidão", "Joanna de Ângelis", 2014],
  ["Quando voltar a primavera", "Amélia Rodrigues", 1996],
  ["Quedas e ascensão", "Victor Hugo", 2015],
  ["Receitas de Paz", "Joanna de Ângelis", 1984],
  ["Reencontro com a Vida", "Manoel Philomeno de Miranda", 2006],
  ["Reflexões Espíritas", "Vianna de Carvalho", 1984],
  ["Rejubila-te em Deus", "Joanna de Ângelis", 2013],
  ["Renova-se", "Marco Prisco", 2015],
  ["Responsabilidade", "Joanna de Ângelis", 1987],
  ["Roteiro de Libertação", "Espíritos diversos", 1981],
  ["Rumo às Estrelas", "Espíritos diversos", 2011],
  ["Rumos libertadores", "Joanna de Ângelis", 1978],
  ["S.O.S. Família", "Joanna de Ângelis", 2014],
  ["Seara do bem", "Joanna de Ângelis", 1964],
  ["Segue em Harmonia", "Joanna de Ângelis", 2015],
  ["Seja Feliz Hoje", "Joanna de Ângelis", 2016],
  ["Sementeira da Fraternidade", "Espíritos diversos", 1963],
  ["Sementes de Vida Eterna", "Espíritos diversos", 1978],
  ["Sendas Luminosas", "Joanna de Ângelis", 1998],
  ["Serenamente em Paz", "Joanna de Ângelis", 2002],
  ["Sexo e Obsessão", "Manoel Philomeno de Miranda", 2002],
  ["Sob a Proteção de Deus", "Espíritos diversos", 2009],
  ["Sol de Esperança", "Espíritos diversos", 2005],
  ["Suave Luz nas Sombras", "João Cléofas", 1977],
  ["Sublime Expiação", "Victor Hugo", 1981],
  ["Temas da Vida e da Morte", "Manoel Philomeno de Miranda", 1989],
  ["Terapêutica de Emergência", "Espíritos diversos", 2002],
  ["Tesouros Libertadores", "Joanna de Ângelis", 2014],
  ["Tormentos da Obsessão", "Manoel Philomeno de Miranda", 2001],
  ["Tramas do Destino", "Manoel Philomeno de Miranda", 1976],
  ["Transição planetária", "Manoel Philomeno de Miranda", 2010],
  ["Transtornos Psiquiátricos e Obsessivos", "Manoel Philomeno de Miranda", 2008],
  ["Trigo de Deus", "Amélia Rodrigues", 2016],
  ["Trilhas da Libertação", "Manoel Philomeno de Miranda", 1996],
  ["Triunfo Pessoal", "Joanna de Ângelis", 2002],
  ["Vida Feliz", "Joanna de Ângelis", 1992],
  ["Vida: Desafios e Soluções", "Joanna de Ângelis", 1997],
  ["Vidas em Triunfo", "Espíritos diversos", 1995],
  ["Vidas Vazias", "Joanna de Ângelis", 2020],
  ["Vigilância", "Joanna de Ângelis", 1987],
  ["Vitória da Vida", "Espíritos diversos", 2019],
  ["Vitória sobre a depressão", "Joanna de Ângelis", 2005],
  ["Vivendo com Jesus", "Amélia Rodrigues", 2013],
  ["Viver e amar", "Joanna de Ângelis", 1985],
];

/**
 * Monta os registros prontos para gravar em `Titulos`.
 *
 * Devolve objeto com as mesmas chaves dos cabeçalhos da aba — quem grava não
 * precisa saber de onde veio.
 */
function montarAcervoBase_() {
  var registros = [];

  OBRAS_CHICO_XAVIER.forEach(function (obra) {
    registros.push({
      titulo: obra[0],
      autor_ou_medium: MEDIUM_CHICO,
      autor_espiritual: obra[1],
      serie: obra[3] ? SERIE_ANDRE_LUIZ : '',
      ordem_na_serie: obra[3] || '',
      observacao: notaDeOrigem_(FONTE_BAURU, obra[2], 'ano na fonte') + (obra[4] || '')
    });
  });

  OBRAS_KARDEC.forEach(function (obra) {
    registros.push({
      titulo: obra[0],
      autor_ou_medium: 'Allan Kardec',
      autor_espiritual: '',
      serie: obra[2] ? SERIE_KARDEC : '',
      ordem_na_serie: obra[2] || '',
      observacao: notaDeOrigem_(FONTE_KARDEC, obra[1], 'ano na fonte')
    });
  });

  OBRAS_CHICO_COMPLEMENTO.forEach(function (obra) {
    var espiritual = obra[1];
    var nota = notaDeOrigem_(FONTE_CAMINHO, obra[2], '1ª ed.');
    if (espiritual) nota += obra[3] || '';
    else nota += ' · autoria a conferir: ' + obra[3];

    registros.push({
      titulo: obra[0],
      // Sem autor espiritual não há médium a declarar: o livro é sobre ele,
      // não dele. Deixar o nome do Chico aqui afirmaria psicografia.
      autor_ou_medium: espiritual ? MEDIUM_CHICO : '',
      autor_espiritual: espiritual,
      serie: '',
      ordem_na_serie: '',
      observacao: nota
    });
  });

  OBRAS_DIVALDO_FRANCO.forEach(function (obra) {
    registros.push({
      titulo: obra[0],
      autor_ou_medium: MEDIUM_DIVALDO,
      autor_espiritual: obra[1],
      serie: '',
      ordem_na_serie: '',
      observacao: notaDeOrigem_(FONTE_DIVALDO, obra[2], 'ano na fonte')
    });
  });

  return registros;
}

/**
 * A nota que fica em `observacao`. Existe para a bibliotecária saber que
 * aquela linha não foi digitada por ninguém da casa e que o ano é de terceiro
 * — se o exemplar na mão discordar, quem manda é o exemplar.
 */
function notaDeOrigem_(fonte, ano, rotuloDoAno) {
  var nota = 'Pré-cadastro (' + fonte + ')';
  if (ano) nota += ' · ' + rotuloDoAno + ': ' + ano;
  return nota;
}

if (typeof module !== 'undefined') {
  module.exports = {
    montarAcervoBase_: montarAcervoBase_,
    OBRAS_CHICO_XAVIER: OBRAS_CHICO_XAVIER,
    OBRAS_KARDEC: OBRAS_KARDEC,
    OBRAS_CHICO_COMPLEMENTO: OBRAS_CHICO_COMPLEMENTO,
    OBRAS_DIVALDO_FRANCO: OBRAS_DIVALDO_FRANCO
  };
}
