/**
 * Acervo base — obras para pré-cadastro.
 *
 * Não é o acervo da casa: é uma lista de obras espíritas conhecidas, para que
 * catalogar um livro vire "achar o título e acrescentar o exemplar" em vez de
 * digitar autoria toda vez. Título sem exemplar aparece na busca marcado como
 * "a casa não tem" e alimenta a lista de doações desejadas — é o D5, e é de
 * propósito.
 *
 * PROCEDÊNCIA. As obras de Chico Xavier vêm da lista pública do Centro
 * Espírita Chico Xavier (Bauru-SP). Só fato bibliográfico foi copiado — nome
 * da obra, autor espiritual e ano. Nenhuma sinopse: sinopse é texto de alguém.
 *
 * O ANO É INDICATIVO. Na fonte ele às vezes é o da primeira edição e às vezes
 * o de uma reimpressão (`Nos Domínios da Mediunidade` aparece como 1985, e a
 * primeira é de 1955). Por isso ele vai para `observacao` e não para lugar
 * nenhum que o sistema use — o ano que vale é o do exemplar na mão, digitado
 * no cadastro do exemplar.
 *
 * A codificação de Kardec foi escrita à mão. São onze obras, e o dado de uma
 * lista de terceiro seria pior que o sabido.
 *
 * PARA ACRESCENTAR MAIS: é só acrescentar linha aqui e rodar a importação de
 * novo. Ela pula o que já existe, então rodar duas vezes não duplica nada.
 */

// Nome de catalogação: formal e popular juntos, como manda a especificação —
// o frequentador pede "um do Chico", não "um do Francisco Cândido".
var MEDIUM_CHICO = 'Francisco Cândido Xavier (Chico Xavier)';

var SERIE_ANDRE_LUIZ = 'A Vida no Mundo Espiritual';
var SERIE_KARDEC = 'Obras Básicas da Codificação';

// [titulo, autor_espiritual, ano, ordem na série (opcional)]
var OBRAS_CHICO_XAVIER = [
  ["A Caminho da Luz", "Emmanuel", 1939],
  ["A Terra e o Semeador", "Emmanuel", 1975],
  ["A Verdade Responde", "Emmanuel", 1990],
  ["A Vida Conta", "Maria Dolores", 1980],
  ["A Vida Escreve", "Hilário Silva", 1960],
  ["A Volta", "Espíritos Diversos", 1993],
  ["A Luz da Oração", "Espíritos Diversos", 1969],
  ["Abrigo", "Emmanuel", 1985],
  ["Ação e Caminho", "Emmanuel / André Luiz", 1987],
  ["Ação e Reação", "André Luiz", 1957, 9],
  ["Ação, Vida e Luz", "Espíritos Diversos", 1991],
  ["Aceitação e Vida", "Margarida Soares", 1989],
  ["Agenda Cristã", "André Luiz", 1948],
  ["Agenda de Luz", "Espíritos Diversos", 1998],
  ["Agora É o Tempo", "Emmanuel", 1984],
  ["Algo Mais", "Emmanuel", 1980],
  ["Alma do Povo", "Cornélio Pires", 1996],
  ["Alma e Coração", "Emmanuel", 1969],
  ["Alma e Luz", "Emmanuel", 1990],
  ["Alma e Vida", "Maria Dolores", 1984],
  ["Alma S em Desfile", "Hilário Silva", 1964],
  ["Alvorada Cristã", "Neio Lúcio", 1949],
  ["Alvorada do Reino", "Emmanuel", 1988],
  ["Amigo", "Emmanuel", 1979],
  ["Amizade", "Meimei", 1976],
  ["Amor e Luz", "Espíritos Diversos", 1977],
  ["Amor e Saudade", "Espíritos Diversos", 1984],
  ["Amor e Verdade", "Espíritos Diversos", 1999],
  ["Amor sem Adeus", "Walter Perrone", 1978],
  ["Anotações da Mediunidade", "Emmanuel", 1995],
  ["Ante o Futuro", "Espíritos Diversos", 1990],
  ["Antenas de Luz", "Laurinho", 1983],
  ["Antologia da Amizade", "Emmanuel", 1995],
  ["Antologia da Caridade", "Espíritos Diversos", 1995],
  ["Antologia da Criança", "Espíritos Diversos", 1979],
  ["Antologia da Esperança", "Espíritos Diversos", 1995],
  ["Antologia da Espiritualidade", "Maria Dolores", 1971],
  ["A Ntologia do Caminho", "Espíritos Diversos", 1997],
  ["Antologia dos Imortais", "Espíritos Diversos", 1963],
  ["Antologia Mediúnica do Natal", "Espíritos Diversos", 1967],
  ["Apelos Cristãos", "Bezerra de Menezes", 1985],
  ["Apostilas da Vida", "André Luiz", 1986],
  ["As Palavras Cantam", "Carlos Augusto", 1993],
  ["Assim Vencerás", "Emmanuel", 1978],
  ["Astronautas do Além", "Espíritos Diversos", 1973],
  ["Atenção", "Emmanuel", 1981],
  ["Através do Tempo", "Espíritos Diversos", 1972],
  ["Aulas da Vida", "Espíritos Diversos", 1981],
  ["Auta de Souza", "Auta de Souza", 1976],
  ["Ave, Cristo!", "Emmanuel", 1953],
  ["Bastão de Arrimo", "Espírito William", 1984],
  ["Bençãos de Amor", "Espíritos Diversos", 1993],
  ["Boa Nova", "Humberto de Campos", 1941],
  ["Brasil, Coração do Mundo, Pátria...", "Humberto de Campos", 1938],
  ["Brilhe Vossa Luz", "Espíritos Diversos", 1987],
  ["Buscas e Acharás", "Emmanuel / André Luiz", 1975],
  ["Calendário Espírita", "Espíritos Diversos", 1974],
  ["Caminho Espírita", "Espíritos Diversos", 1967],
  ["Caminho Iluminado", "Emmanuel", 1998],
  ["Caminho, Verdade e Vida", "Emmanuel", 1949],
  ["Caminhos", "Emmanuel", 1981],
  ["Caminhos da Fé", "Cornélio Pires", 1997],
  ["Caminhos da Vida", "Cornélio Pires", 1997],
  ["Caminhos de Volta", "Cornélio Pires", 1975],
  ["Caminhos do Amor", "Maria Dolores", 1983],
  ["Canais da Vida", "Emmanuel", 1986],
  ["Canteiro de Ideias", "Espíritos Diversos", 1999],
  ["Caravana de Amor", "Espíritos Diversos", 1984],
  ["Caridade", "Espíritos Diversos", 1978],
  ["Cartas de uma Morta", "Maria João de Deus", 1935],
  ["Cartas do Coração", "Espíritos Diversos", 1952],
  ["Cartas do Evangelho", "Casimiro Cunha", 1941],
  ["Cartas e Crônicas", "Irmão X", 1966],
  ["Cartilha da Natureza", "Casimiro Cunha", 1944],
  ["Cartilha do Bem", "Meimei", 1962],
  ["Ceifa de Luz", "Emmanuel", 1962],
  ["Centelhas", "Emmanuel", 1992],
  ["Chico Xavier - Dos Hippies aos Problemas do Mundo", "Espíritos Diversos", 1972],
  ["Cidade no Além", "André Luiz / Lucius", 1999],
  ["Cinquenta Anos Depois", "Emmanuel", 1940],
  ["Claramente Vivos", "Espíritos Diversos", 1979],
  ["Coisas Deste Mundo", "Cornélio Pires", 1977],
  ["Coletâneas do Além", "Espíritos Diversos", 1945],
  ["Comandos do Amor", "Espíritos Diversos", 1988],
  ["Compaixão", "Emmanuel", 1993],
  ["Confia e Serve", "Espíritos Diversos", 1989],
  ["Construção do Amor", "Emmanuel", 1988],
  ["Continuidade", "Espíritos Diversos", 1990],
  ["Contos Desta e Doutra Vida", "Irmão X", 1964],
  ["Contos e Apólogos", "Irmão X", 1958],
  ["Convivência", "Emmanuel", 1983],
  ["Coração e Vida", "Maria Dolores", 1978],
  ["Corações Renovados", "Espíritos Diversos", 1988],
  ["Coragem", "Espíritos Diversos", 1971],
  ["Correio do Além", "Espíritos Diversos", 1983],
  ["Correio Fraterno", "Espíritos Diversos", 1970],
  ["Crer e Agir", "Emmanuel / Irmão José", 1985],
  ["Crônicas de Além-túmulo", "Humberto de Campos", 1937],
  ["Dádivas de Amor", "Maria Dolores", 1990],
  ["Dádivas Espirituais", "Espíritos Diversos", 1994],
  ["Degraus da Vida", "Cornélio Pires", 1996],
  ["Desobsessão", "André Luiz", 1964],
  ["Deus Sempre", "Emmanuel", 1976],
  ["Diário de Bençãos", "Cristiane", 1983],
  ["Dicionário da Alma", "Espíritos Diversos", 1964],
  ["Dinheiro", "Emmanuel", 1985],
  ["Doutrina - Escola", "Espíritos Diversos", 1996],
  ["Doutrina e Aplicação", "Espíritos Diversos", 1989],
  ["Doutrina e Vida", "Espíritos Diversos", 1987],
  ["E a Vida Continua", "André Luiz", 1968, 13],
  ["Educandário de Luz", "Espíritos Diversos", 1984],
  ["Elenco de Familiares", "Espíritos Diversos", 1995],
  ["Eles Voltaram", "Espíritos Diversos", 1981],
  ["Emmanuel", "Emmanuel", 1938],
  ["Encontro de Paz", "Espíritos Diversos", 1973],
  ["Encontro Marcado", "Emmanuel", 1967],
  ["Encontros no Tempo", "Espíritos Diversos", 1979],
  ["Endereços de Paz", "André Luiz", 1982],
  ["Entender Conversando", "Emmanuel", 1983],
  ["Entre a Terra e o Céu", "André Luiz", 1954, 7],
  ["Entre Duas Vidas", "Espíritos Diversos", 1973],
  ["Entre Irmãos de Outras Terras", "Espíritos Diversos", 1966],
  ["Entrevistas", "Emmanuel", 1971],
  ["Enxugando Lágrimas", "Espíritos Diversos", 1978],
  ["Escada de Luz", "Espíritos Diversos", 1999],
  ["Escola no Além", "Cláudia P. Galasse", 1988],
  ["Escrínio de Luz", "Emmanuel", 1973],
  ["Escultores de Alma", "Espíritos Diversos", 1987],
  ["Esperança e Alegria", "Espíritos Diversos", 1987],
  ["Esperança e Luz", "Espíritos Diversos", 1993],
  ["Esperança e Vida", "Espíritos Diversos", 1984],
  ["Estamos no Além", "Espíritos Diversos", 1982],
  ["Estamos Vivos", "Espíritos Diversos", 1992],
  ["Estante da Vida", "Irmão X", 1969],
  ["Estradas e Destinos", "Espíritos Diversos", 1986],
  ["Estude e Viva", "Emmanuel / André Luiz", 1965],
  ["Evangelho em Casa", "Meimei", 1960],
  ["Evolução em Dois Mundos", "André Luiz", 1959, 10],
  ["Excursão de Paz", "Espíritos Diversos", 1990],
  ["Falando à Terra", "Espíritos Diversos", 1950],
  ["Fé", "Espíritos Diversos", 1984],
  ["Feliz Regresso", "Espíritos Diversos", 1980],
  ["Fonte de Paz", "Espíritos Diversos", 1987],
  ["Fonte Viva", "Emmanuel", 1956],
  ["Fulgor no Entardecer", "Espíritos Diversos", 1991],
  ["Gabriel", "Gabriel", 1982],
  ["Gaveta de Esperança", "Laurinho", 1980],
  ["Gotas de Luz", "Casimiro Cunha", 1953],
  ["Gotas de Paz", "Emmanuel", 1993],
  ["Gratidão e Paz", "Espíritos Diversos", 1988],
  ["Há Dois Mil Anos", "Emmanuel", 1940],
  ["História de Maricota", "Casimiro Cunha", 1947],
  ["Histórias e Anotações", "Irmão X", 1989],
  ["Hoje", "Emmanuel", 1984],
  ["Horas de Luz", "Espíritos Diversos", 1984],
  ["Humorismo no Além", "Espíritos Diversos", 1983],
  ["Ideal Espírita", "Espíritos Diversos", 1963],
  ["Ideias e Ilustrações", "Espíritos Diversos", 1970],
  ["Indulgência", "Emmanuel", 1989],
  ["Instruções Psicofônicas", "Espíritos Diversos", 1956],
  ["Instrumentos do Tempo", "Emmanuel", 1974],
  ["Intervalos", "Espíritos Diversos", 1981],
  ["Irmã Vera Cruz", "Vera Cruz", 1980],
  ["Irmão", "Emmanuel", 1980],
  ["Janela para a Vida", "Espíritos Diversos", 1980],
  ["Jardim da Infância", "João de Deus", 1947],
  ["Jesus no Lar", "Neio Lucio", 1950],
  ["Joia", "Emmanuel", 1985],
  ["Jovens no Além", "Espíritos Diversos", 1974],
  ["Juca Lambisca", "Casimiro Cunho", 1961],
  ["Juntos Venceremos", "Espíritos Diversos", 1985],
  ["Justiça Divina", "Emmanuel", 1962],
  ["Lázaro Redivivo", "Irmão X", 1945],
  ["Lealdade", "Maurício G. Henrique", 1982],
  ["Leis de Amor", "Emmanuel", 1963],
  ["Libertação", "André Luiz", 1949, 6],
  ["Linha Duzentos", "Emmanuel", 1981],
  ["Lira Imortal", "Espíritos Diversos", 1939],
  ["Livro da Esperança", "Emmanuel", 1964],
  ["Livro de Respostas", "Emmanuel", 1980],
  ["Luz Acima", "Irmão X", 1948],
  ["Luz Bendita", "Emmanuel / Esp. Diversos", 1977],
  ["Luz no Caminho", "Emmanuel", 1991],
  ["Luz no Lar", "Espíritos Diversos", 1968],
  ["Mãe", "Espíritos Diversos", 1971],
  ["Mais Vida", "Espíritos Diversos", 1981],
  ["Mãos Marcadas", "Espíritos Diversos", 1972],
  ["Mãos Unidas", "Emmanuel", 1972],
  ["Marcas do Caminho", "Espíritos Diversos", 1979],
  ["Maria Dolores", "Maria Dolores", 1977],
  ["Material de Construção", "Emmanuel", 1982],
  ["Mecanismos da Mediunidade", "André Luiz", 1960, 11],
  ["Mediunidade e Sintonia", "Emmanuel", 1985],
  ["Mensagem do Pequeno Morto", "Neio Lúcio", 1947],
  ["Mentores e Seareiros", "Espíritos Diversos", 1993],
  ["Migalha", "Emmanuel", 1993],
  ["Missionários da Luz", "André Luiz", 1945, 3],
  ["Momento", "Emmanuel", 1994],
  ["Momentos de Paz", "Emmanuel", 1980],
  ["Moradias de Luz", "Emmanuel", 1980],
  ["Ninguém Morre", "Espíritos Diversos", 1983],
  ["No Mundo Maior", "André Luiz", 1947, 5],
  ["No Portal da Luz", "Emmanuel", 1967],
  ["Nos Domínios da Mediunidade", "André Luiz", 1985, 8],
  ["Nós", "Emmanuel", 1955],
  ["Nosso Lar", "André Luiz", 1944, 1],
  ["Nosso Livro", "Espíritos Diversos", 1950],
  ["Notas do Mais Além", "Espíritos Diversos", 1995],
  ["Notícias do Além", "Espíritos Diversos", 1980],
  ["Novas Mensagens", "Humberto de Campos", 1940],
  ["Novo Mundo", "Emmanuel", 1991],
  ["O Caminho Oculto", "Veneranda", 1947],
  ["O Consolador", "Emmanuel", 1941],
  ["O Esperanto Como Revelação", "Francisco V. P. Lorenz", 1975],
  ["O Espírito da Verdade", "Emmanuel", 1962],
  ["O Espírito de Cornélio Pires", "Cornélio Pires", 1965],
  ["O Essencial", "Emmanuel", 1985],
  ["Obreiros da Vida Eterna", "André Luiz", 1946, 4],
  ["Oferta de Amigo", "Cornélio Pires", 1996],
  ["Opinião Espírita", "Emmanuel / André Luiz", 1996],
  ["Orvalhos de Luz", "Espíritos Diversos", 1969],
  ["Os Filhos do Grande Rei", "Veneranda", 1947],
  ["Os Mensageiros", "André Luiz", 1944, 2],
  ["Paciência", "Emmanuel", 1983],
  ["Páginas de Fé", "Espíritos Diversos", 1988],
  ["Páginas do Coração", "Irmã Candoca", 1951],
  ["Pai Nosso", "Meimei", 1952],
  ["Palavras da Coragem", "Espíritos Diversos", 1987],
  ["Palavras de Chico Xavier", "Emmanuel", 1995],
  ["Palavras de Emmanuel", "Emmanuel", 1954],
  ["Palavras de Vida Eterna", "Emmanuel", 1965],
  ["Palavras do Coração", "Meimei", 1982],
  ["Palavras do Infinito", "Emmanuel", 1950],
  ["Pão Nosso", "Emmanuel", 1950],
  ["Parnaso de Além Túmulo", "Espíritos Diversos", 1932],
  ["Passos da Vida", "Espíritos Diversos", 1969],
  ["Paulo e Estevão", "Emmanuel", 1942],
  ["Paz", "Emmanuel", 1942],
  ["Paz e Amor", "Cornélio Pires", 1996],
  ["Paz e Libertação", "Espíritos Diversos", 1996],
  ["Paz e Renovação", "Espíritos Diversos", 1970],
  ["Pedaços da Vida", "Cornélio Pires", 1997],
  ["Pensamento e Vida", "Emmanuel", 1958],
  ["Perante Jesus", "Emmanuel", 1990],
  ["Perdão e Vida", "Espíritos Diversos", 1999],
  ["Pérolas de Luz", "Emmanuel", 1992],
  ["Pérolas do Além", "Espíritos Diversos", 1952],
  ["Pétalas de Primavera", "Espíritos Diversos", 1990],
  ["Pétalas da Vida", "Cornélio Pires", 1997],
  ["Pinga Fogo - Primeira Entrevista", "Espíritos Diversos", 1971],
  ["Plantão de Respostas - Pinga Fogo II", "Espíritos Diversos", 1995],
  ["Poetas Redivivos", "Espíritos Diversos", 1969],
  ["Pontos e Contos", "Irmão X", 1951],
  ["Porto de Alegria", "Espíritos Diversos", 1990],
  ["Praça da Amizade", "Espíritos Diversos", 1982],
  ["Presença de Laurinho", "Laurinho", 1982],
  ["Pronto Socorro", "Emmanuel", 1980],
  ["Quem São", "Espíritos Diversos", 1980],
  ["Recados do Além", "Emmanuel", 1978],
  ["Recanto de Paz", "Espíritos Diversos", 1976],
  ["Reencontros", "Espíritos Diversos", 1982],
  ["Refúgio", "Emmanuel", 1989],
  ["Relatos da Vida", "Irmão X", 1988],
  ["Relicários de Luz", "Espíritos Diversos", 1962],
  ["Religião dos Espíritos", "Emmanuel", 1960],
  ["Renascimento Espiritual", "Espíritos Diversos", 1995],
  ["Renúncia", "Emmanuel", 1943],
  ["Reportagens de Além Túmulo", "Humberto de Campos", 1943],
  ["Retornaram Contando", "Espíritos Diversos", 1984],
  ["Retratos da Vida", "Cornélio Pires", 1973],
  ["Rosas com Amor", "Espíritos Diversos", 1973],
  ["Roteiro", "Emmanuel", 1952],
  ["Rumo Certo", "Emmanuel", 1971],
  ["Rumos da Vida", "Espíritos Diversos", 1981],
  ["Saudação do Natal", "Espíritos Diversos", 1996],
  ["Seara de Fé", "Espíritos Diversos", 1981],
  ["Seara dos Médiuns", "Emmanuel", 1961],
  ["Segue-me", "Emmanuel", 1973],
  ["Semente", "Emmanuel", 1993],
  ["Sementes de Luz", "Espíritos Diversos", 1986],
  ["Senda para Deus", "Espíritos Diversos", 1997],
  ["Sentinelas da Alma", "Meimei", 1982],
  ["Sentinelas da Luz", "Espíritos Diversos", 1990],
  ["Servidores no Além", "Espíritos Diversos", 1989],
  ["Sexo e Destino", "André Luiz", 1963, 12],
  ["Sinal Verde", "André Luiz", 1971],
  ["Sínteses Doutrinárias", "Espíritos Diversos", 1995],
  ["Somente Amor", "Maria Dolores / Meimei", 1978],
  ["Sorrir e Pensar", "Espíritos Diversos", 1983],
  ["Taça de Luz", "Espíritos Diversos", 1972],
  ["Tão Fácil", "Espíritos Diversos", 1984],
  ["Temas da Vida", "Espíritos Diversos", 1987],
  ["Tempo de Luz", "Espíritos Diversos", 1979],
  ["Tempo e Amor", "Espíritos Diversos", 1983],
  ["Tempo e Nós", "Emmanuel / André Luiz", 1993],
  ["Tende Bom Ânimo", "Espíritos Diversos", 1987],
  ["Tesouro de Alegria", "Espíritos Diversos", 1993],
  ["Timbolão", "Casimiro Cunha", 1962],
  ["Tintino... O Espetáculo Continua", "Francisca Clotilde", 1976],
  ["Tocando o Barco", "Emmanuel", 1983],
  ["Toques da Vida", "Cornélio Pires", 1997],
  ["Trilha de Luz", "Emmanuel", 1990],
  ["Trovadores do Além", "Espíritos Diversos", 1965],
  ["Trovas da Vida", "Cornélio Pires", 1999],
  ["Trovas do Coração", "Cornélio Pires", 1997],
  ["Trovas do Mais Além", "Espíritos Diversos", 1971],
  ["Trovas do Outro Mundo", "Espíritos Diversos", 1968],
  ["União em Jesus", "Espíritos Diversos", 1994],
  ["Viajor", "Emmanuel", 1984],
  ["Vida e Sexo", "Emmanuel", 1970],
  ["Vida em Vida", "Espíritos Diversos", 1980],
  ["Vinha de Luz", "Emmanuel", 1952],
  ["Visão Nova", "Emmanuel", 1986],
  ["Vitória", "Espíritos Diversos", 1986],
  ["Vivendo Sempre", "Espíritos Diversos", 1981],
  ["Viveremos Sempre", "Espíritos Diversos", 1994],
  ["Volta Bocage", "Manuel M. B. Bocage", 1947],
  ["Voltei", "Irmão Jacob", 1949],
  ["Vozes da Outra Margem", "Espíritos Diversos", 1986],
  ["Vozes do Grande Além", "Espíritos Diversos", 1957],
];

// [titulo, ano, ordem entre as obras básicas (opcional)]
var OBRAS_KARDEC = [
  ["O Livro dos Espíritos", 1857, 1],
  ["O Livro dos Médiuns", 1861, 2],
  ["O Evangelho segundo o Espiritismo", 1864, 3],
  ["O Céu e o Inferno", 1865, 4],
  ["A Gênese", 1868, 5],
  ["O que é o Espiritismo", 1859],
  ["O Espiritismo em sua Mais Simples Expressão", 1862],
  ["Instruções Práticas sobre as Manifestações Espíritas", 1858],
  ["Viagem Espírita em 1862", 1862],
  ["Obras Póstumas", 1890],
  ["Revista Espírita", 1858],
];

/**
 * Monta os registros prontos para gravar em `Titulos`.
 *
 * Devolve objeto com as mesmas chaves dos cabeçalhos da aba — quem grava não
 * precisa saber de onde veio.
 */
function montarAcervoBase_() {
  var registros = [];

  OBRAS_CHICO_XAVIER.forEach(function (obra) {
    registros.push({
      titulo: obra[0],
      autor_ou_medium: MEDIUM_CHICO,
      autor_espiritual: obra[1],
      serie: obra[3] ? SERIE_ANDRE_LUIZ : '',
      ordem_na_serie: obra[3] || '',
      observacao: notaDeOrigem_('lista do CE Chico Xavier, Bauru', obra[2])
    });
  });

  OBRAS_KARDEC.forEach(function (obra) {
    registros.push({
      titulo: obra[0],
      autor_ou_medium: 'Allan Kardec',
      autor_espiritual: '',
      serie: obra[2] ? SERIE_KARDEC : '',
      ordem_na_serie: obra[2] || '',
      observacao: notaDeOrigem_('codificação de Kardec', obra[1])
    });
  });

  return registros;
}

/**
 * A nota que fica em `observacao`. Existe para a bibliotecária saber que
 * aquela linha não foi digitada por ninguém da casa e que o ano é palpite de
 * terceiro — se o exemplar na mão discordar, quem manda é o exemplar.
 */
function notaDeOrigem_(fonte, ano) {
  var nota = 'Pré-cadastro (' + fonte + ')';
  if (ano) nota += ' · ano na fonte: ' + ano;
  return nota;
}

if (typeof module !== 'undefined') {
  module.exports = {
    montarAcervoBase_: montarAcervoBase_,
    OBRAS_CHICO_XAVIER: OBRAS_CHICO_XAVIER,
    OBRAS_KARDEC: OBRAS_KARDEC
  };
}
